version: '3.9'
# Example cluster for the HTTP runtime.
#
# How to use locally:
#  1) Build and start: `docker compose -f dslabs/runtime/docker-compose.yml up --build`
#  2) Open the dashboard: http://localhost:8501
#  3) Observe GET /state responses from each node.
services:
  n1: &node
    build: .
    environment:
      - NODE_ID=n1
      - MY_URL=http://n1:8000
      - PEERS=n1:http://n1:8000,n2:http://n2:8000,n3:http://n3:8000
    command: ['python','-m','dslabs.runtime.run_node']
  n2:
    <<: *node
    environment:
      - NODE_ID=n2
      - MY_URL=http://n2:8000
      - PEERS=n1:http://n1:8000,n2:http://n2:8000,n3:http://n3:8000
  n3:
    <<: *node
    environment:
      - NODE_ID=n3
      - MY_URL=http://n3:8000
      - PEERS=n1:http://n1:8000,n2:http://n2:8000,n3:http://n3:8000
  dashboard:
    build: .
    command: ['python','-m','streamlit','run','dslabs/dashboard/app.py','--server.port','8501','--server.headless','true']
    ports: ['8501:8501']
networks:
  default:
    name: dsnet
